<?php

namespace Tests\Feature;

use App\Models\Agencies;
use App\Models\Appraisals;
use App\Models\BusinessLine;
use App\Models\Calls;
use App\Models\Companies;
use App\Models\Opportunities;
use App\Models\Talks;
use App\Models\TalksAppraisals;
use App\Models\TalksCalls;
use App\Models\TalksOpportunities;
use App\Models\TalksTraffic;
use App\Models\Tickets;
use App\Models\Traffic;
use App\Models\User;
use App\Models\Users;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class HistoryTalksTest extends TestCase
{
    use RefreshDatabase, WithFaker;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setInitDataUser();
    }

    /** @test */
    public function getTalks()
    {
        $response = $this->get('/talksHistory/0201599479');
        $content = json_decode($response->content());
        $expectedTalks = Talks::where('numero_identificacion', '0201599479')
            ->where('deleted', '0')
            ->orderBy('date_entered', 'desc')
            ->pluck('name');

        $this->assertEquals($expectedTalks[0], $content->talksHistory[0]->name);
        $response->assertStatus(202);
    }

    /** @test */
    public function getTalksAsesor()
    {
        $response = $this->get('/talksHistory/0201599479');
        $content = json_decode($response->content());
        $expectedTalks = Talks::where('numero_identificacion', '0201599479')
            ->where('deleted', '0')
            ->orderBy('date_entered', 'desc')
            ->pluck('assigned_user_id');
        $asesor = Users::where('id', $expectedTalks[0])->first();
        $this->assertEquals(json_decode($asesor), $content->talksHistory[0]->asesor);
        $response->assertStatus(202);
    }


    /** @test */
    public function getTalksTraffic()
    {
        $response = $this->get('/talksHistory/0201599479');
        $content = json_decode($response->content());
        $expectedTalks = $this->getExpectedTalks();
        $talksTraffic = TalksTraffic::where('cb_negociacion_cb_traficocontrolcb_negociacion_ida', $expectedTalks[0])->pluck('cb_negociacion_cb_traficocontrolcb_traficocontrol_idb');
        $expectedTraffics = Traffic::whereIn('id', $talksTraffic)->where('deleted', 0)->orderBy('date_entered', 'desc')->get();

        foreach ($expectedTraffics as $traffic)
        {
            $traffic->user = Users::where('id', $traffic->assigned_user_id)->first();
            $traffic->agency = Agencies::where('id', $traffic->cb_agencias_id_c)->first();
        }

        $this->assertEquals(json_decode($expectedTraffics), $content->talksHistory[0]->traffic);
        $response->assertStatus(202);
    }

    /** @test */
    public function getTalksCalls()
    {
        $response = $this->get('/talksHistory/0201599479');
        $content = json_decode($response->content());
        $expectedTalks = $this->getExpectedTalks();
        $talksCalls = TalksCalls::where('cb_negociacion_callscb_negociacion_ida', $expectedTalks[0])->pluck('cb_negociacion_callscalls_idb');
        $expectedCalls = Calls::whereIn('id', $talksCalls)->where('deleted', 0)->orderBy('date_entered', 'desc')->get();

        $this->assertEquals(json_decode($expectedCalls), $content->talksHistory[0]->calls);
        $response->assertStatus(202);
    }

    /** @test */
    public function getTalksOpportunities()
    {
        $response = $this->get('/talksHistory/0201599479');
        $content = json_decode($response->content());
        $expectedTalks = $this->getExpectedTalks();
        $talksOpportunities = TalksOpportunities::where('cb_negociacion_opportunitiescb_negociacion_ida', $expectedTalks[1])->pluck('cb_negociacion_opportunitiesopportunities_idb');
        $expectedOpportunities = Opportunities::whereIn('id', $talksOpportunities)
            ->join('opportunities_cstm', 'opportunities.id', '=', 'opportunities_cstm.id_c')
            ->where('deleted', 0)
            ->orderBy('date_entered', 'desc')
            ->get();

        foreach ($expectedOpportunities as $opportunity)
        {
            $opportunity->user = Users::where('id', $opportunity->assigned_user_id)->first();
            $opportunity->agency = Agencies::where('id', $opportunity->cb_agencias_id_c)->first();
            $opportunity->business_line = BusinessLine::where('id', $opportunity->cb_lineanegocio_id_c)->first();
        }

        $this->assertEquals(json_decode($expectedOpportunities), $content->talksHistory[1]->opportunities);
        $response->assertStatus(202);
    }

    /** @test */
    public function getTalksAppraisals()
    {
        $response = $this->get('/talksHistory/0201599479');
        $content = json_decode($response->content());
        $expectedTalks = $this->getExpectedTalks();
        $talksAppraisals = TalksAppraisals::where('cb_negociacion_cb_avaluoscb_negociacion_ida', $expectedTalks[2])->pluck('cb_negociacion_cb_avaluoscb_avaluos_idb');
        $expectedAppraisals = Appraisals::whereIn('id', $talksAppraisals)->where('deleted', 0)->orderBy('date_entered', 'desc')->get();

        $this->assertEquals(json_decode($expectedAppraisals), $content->talksHistory[2]->appraisals);
        $response->assertStatus(202);
    }

    public function getExpectedTalks(){
        return Talks::where('numero_identificacion', '0201599479')
            ->where('deleted', '0')
            ->orderBy('date_entered', 'desc')
            ->pluck('id');
    }
}
