<?php

namespace Tests\Feature;

use App\Models\Tickets;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

class TicketsTest extends TestCase
{
    use RefreshDatabase, WithFaker;
    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->setInitDataUserSanctum();
        $this->setInitDataTicket();
    }

    /** @test */
    public function create_ticket_succesfull()
    {
        $response = $this->json('POST', $this->baseUrl . 'tickets', $this->dataTicket);
        $content = json_decode($response->content());

        $response->assertStatus(200);
        $this->assertNotNull($content->data->ticket_id);
        $this->assertNotNull($content->data->ticket_name);
        $this->assertNotNull($content->data->interaction_id);
        $this->assertEquals('https://sugarcrm.casabaca.com/#cbt_Tickets/'. $content->data->ticket_id, $content->data->ticket_url);

        $ticket = Tickets::find($content->data->ticket_id);
        $this->assertEquals($ticket->numero_identificacion, $this->dataTicket['datosSugarCRM']['numero_identificacion']);
        $this->assertEquals($ticket->fuente, '2');
        $this->assertEquals($ticket->tipo_identificacion, $this->dataTicket['datosSugarCRM']['tipo_identificacion']);
        $this->assertEquals($ticket->email, $this->dataTicket['datosSugarCRM']['email']);
        $this->assertEquals($ticket->nombres, $this->dataTicket['datosSugarCRM']['nombres']);
        $this->assertEquals($ticket->estado, $this->dataTicket['datosSugarCRM']['estado']);
        $this->assertEquals($ticket->linea_negocio, $this->dataTicket['datosSugarCRM']['linea_negocio']);
        $this->assertEquals($ticket->id, $ticket->ticketsCstm->id_c);
        $this->assertEquals($ticket->estado, $ticket->ticketsCstm->flag_estados_c);
        $this->assertEquals($ticket->ticketsCstm->porcentaje_discapacidad_c, $this->dataTicket['datosSugarCRM']['porcentaje_discapacidad']);
        $this->assertEquals($ticket->ticketsCstm->medio_c, $this->dataTicket['datosSugarCRM']['medio']);
        $this->assertEquals($ticket->ticketsCstm->campaign_id_c, $this->dataTicket['datosSugarCRM']['campania']);

        $interaction = $ticket->interacciones[0];
        $this->assertEquals($interaction->numero_identificacion, $this->dataTicket['datosSugarCRM']['numero_identificacion']);
        $this->assertEquals($interaction->fuente, '2');
        $this->assertEquals($interaction->tipo_identificacion, $this->dataTicket['datosSugarCRM']['tipo_identificacion']);
        $this->assertEquals($interaction->email, $this->dataTicket['datosSugarCRM']['email']);
        $this->assertEquals($interaction->nombre, $this->dataTicket['datosSugarCRM']['nombres']);
        $this->assertEquals($interaction->nombre, $this->dataTicket['datosSugarCRM']['nombres']);
        $this->assertEquals($interaction->cb_lineanegocio_id_c, 'd8365338-9206-11e9-a7c3-000c297d72b1');
        $this->assertEquals("Nuevos", $interaction->linea_negocio);
        $interactionCstm = $interaction->interaccionesCstm()->first();
        $this->assertEquals($interactionCstm->medio_c, $this->dataTicket['datosSugarCRM']['medio']);
        $this->assertEquals($interactionCstm->campaign_id_c, $this->dataTicket['datosSugarCRM']['campania']);
    }

    /** @test */
    public function create_ticket_with_data_invalid()
    {
        $data = [
            'datosSugarCRM' => [
                'tipo_identificacion'=>'001',
                'email'=>'roberto@gmailcom',
                'nombres'=>'Prueba',
                'estado'=> 100,
                'linea_negocio'=>  1000,
                'user_name'=>  'CG_RAMOS',
                'medio' => '123465',
                'campania' => '123'
            ]
        ];

        $response = $this->json('POST', $this->baseUrl . 'tickets', $data);
        $content = json_decode($response->content());

        $response->assertStatus(422);
        $err_no_identificacion = 'datosSugarCRM.numero_identificacion';
        $err_tipo_identificacion = 'datosSugarCRM.tipo_identificacion';
        $err_linea_negocio = 'datosSugarCRM.linea_negocio';
        $err_medio = 'datosSugarCRM.medio';
        $err_email = 'datosSugarCRM.email';
        $err_campania = 'datosSugarCRM.campania';

        $this->assertEquals($content->errors->$err_no_identificacion[0], 'Identificación es requerida');
        $this->assertEquals($content->errors->$err_tipo_identificacion[0], 'Tipo de identificación no contiene un valor válido, valores válidos: C(Cedula),P(Pasaporte), R(RUC)');
        $this->assertEquals($content->errors->$err_linea_negocio[0], 'Linea no contiene un valor válido, valores válidos: 1(Postventa),2(Nuevos), 3(Seminuevos), 4(Exonerados)');
        $this->assertEquals($content->errors->$err_email[0], 'Email debe ser un email válido');
        $this->assertEquals($content->errors->$err_medio[0], 'Medio no contiene un valor válido, valores válidos: {"5":"Empleados","6":"App Talleres"}');
        $this->assertEquals($content->errors->$err_campania[0], 'Campaña no existe en SUGAR');
    }

    /** @test */
    public function create_ticket_with_data_incomplete()
    {
        $data = [
            'datosSugarCRM' => [
                'numero_identificacion'=>'1234567890',
                'email'=>'roberto@gmail.com',
                'nombres'=>'Prueba',
                'linea_negocio'=>  1000
            ]
        ];

        $response = $this->json('POST', $this->baseUrl . 'tickets', $data);
        $content = json_decode($response->content());
        $response->assertStatus(422);
        $err_tipo_identificacion = 'datosSugarCRM.tipo_identificacion';

        $this->assertEquals($content->errors->$err_tipo_identificacion[0], 'Tipo de identificación es requerida para el número de identificación');
    }

    /** @test */
    public function create_ticket_with_invalid_username()
    {
        $data = [
            'datosSugarCRM' => [
                'numero_identificacion'=>'1234567891002',
                'tipo_identificacion'=>'C',
                'email'=>'roberto@gmail.com',
                'celular'=>'0987517283',
                'nombres'=>'Prueba',
                'apellidos'=>'Apellidos',
                'estado'=> 4,
                'linea_negocio'=>  4,
                'user_name'=> 'not_exists',
                'id_interaccion_inconcert' => 'id_interaccion_inconcert',
                'tipo_transaccion' => '1'
            ]
        ];

        $response = $this->json('POST', $this->baseUrl . 'tickets', $data);
        $content = json_decode($response->content());
        $response->assertStatus(422);
        $err_user_name = 'datosSugarCRM.user_name';

        $this->assertEquals($content->errors->$err_user_name[0], 'User-name inválido, asesor  no se encuentra registrado');
    }

    /** @test */
    public function update_ticket_success()
    {
        $this->dataTicket['datosSugarCRM']['numero_identificacion'] = $this->faker->numerify('##########');
        $response = $this->json('POST', $this->baseUrl . 'tickets', $this->dataTicket);
        $content_created = json_decode($response->content());
        $response->assertStatus(200);

        $data = [
            'datosSugarCRM' => [
                'motivo_cierre' => 'abandono_chat'
            ]
        ];

        $response = $this->json('POST', $this->baseUrl . 'close_ticket/'. $content_created->data->ticket_id, $data);

        $content_update = json_decode($response->content());
        $response->assertStatus(200);
        $this->assertEquals($content_update->data->ticket_id, $content_created->data->ticket_id);
    }

    /** @test */
    public function create_contact_ticket_success()
    {
        $response = $this->json('POST', $this->baseUrl . 'tickets', $this->dataTicket);
        $content = json_decode($response->content());
        $response->assertStatus(200);
        $this->assertNotNull($content->data->ticket_id);
        $this->assertNotNull($content->data->ticket_name);
        $this->assertNotNull($content->data->interaction_id);

        $ticket = Tickets::find($content->data->ticket_id);
        $contact = $ticket->contacts()->first();
        $emailContact = $contact->emailAddress()->first();

        $this->assertEquals("FREDDY MANUEL",$contact->first_name);
        $this->assertEquals("VARGAS JACOME",$contact->last_name);
        $this->assertEquals("frvr@gmail.com",$emailContact->email_address);
    }

    /** @test */
    public function update_ticket_no_exists()
    {
        $data = [
            'datosSugarCRM' => [
                'motivo_cierre' => 'solo_informacion'
            ]
        ];
        $response = $this->json('POST', $this->baseUrl . 'close_ticket/id_not_exists', $data);

        $content_update = json_decode($response->content());

        $response->assertStatus(404);
        $this->assertEquals($content_update->error, 'Ticket no existe, id inválido');
    }

    /** @test */
    public function update_ticket_error_status()
    {
        $this->dataTicket['datosSugarCRM']['numero_identificacion'] = $this->faker->numerify('##########');
        $response = $this->json('POST', $this->baseUrl . 'tickets', $this->dataTicket);
        $content_created = json_decode($response->content());
        $response->assertStatus(200);
        $data = [
            'datosSugarCRM' => [
                'motivo_cierre' => 'other_rason'
            ]
        ];
        $response = $this->json('POST', $this->baseUrl . 'close_ticket/'. $content_created->data->ticket_id, $data);

        $content_update = json_decode($response->content());

        $response->assertStatus(422);
        $err_motivo_cierre = 'datosSugarCRM.motivo_cierre';

        $this->assertEquals($content_update->errors->$err_motivo_cierre[0], 'Motivo de cierre no contiene un valor válido, valores válidos: abandono_chat,solo_informacion,desiste,no_contesta,compra_futura');

    }
}
