<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class CuotaAlcance extends Model
{
    use HasFactory;
    /*
        cambiar la conexion
        */
    protected $connection = 'base_intermedia';
    protected $table='cuota_alcance';
    protected $fillable = [
        'cuaota_alcance',
        'cuota',
        'descuento',
        'entrada',
        'f_banco',
        'f_saldo_financiar',
        'f_tiempo_financiar',
        'fecha_alcance',
        'financiamiento',
        'financiera',
        'ib_anios_1',
        'ib_anios_2',
        'ib_banco_1',
        'ib_banco_2',
        'ib_no_cuenta_1',
        'ib_no_cuenta_2',
        'ib_tipo_cuenta_1',
        'ib_tipo_cuenta_2',
        'intereses',
        'iva',
        'neto',
        'no_cuotas',
        'oc_empresa',
        'oc_orden',
        'oc_valor',
        'orden_compra',
        'otros',
        'otros_cargos',
        'otros_formas',
        'otros_valor',
        'poliza',
        'poliza_banco',
        'poliza_fecha_vencimiento',
        'poliza_valor',
        'porcentaje',
        'rc_descripcion_ubicacion_1',
        'rc_descripcion_ubicacion_2',
        'rc_descripcion_ubicacion_3',
        'rc_descripcion_ubicacion_4',
        'rc_empresa_1',
        'rc_empresa_2',
        'rc_monto_compra_1',
        'rc_monto_compra_2',
        'rc_tiempo_relacion_1',
        'rc_tiempo_relacion_2',
        'rc_tipo_empresa_1',
        'rc_tipo_empresa_2',
        'rc_total_bienes',
        'rc_valor_comercial_1',
        'rc_valor_comercial_2',
        'rc_valor_comercial_3',
        'rc_valor_comercial_4',
        'rc_valor_deuda_1',
        'rc_valor_deuda_2',
        'rc_valor_deuda_3',
        'rc_valor_deuda_4',
        'rf_apellidos_1',
        'rf_apellidos_2',
        'rf_celular_1',
        'rf_celular_2',
        'rf_nombres_1',
        'rf_nombres_2',
        'rf_parentezco_1',
        'rf_parentezco_2',
        'rf_provincia_1',
        'rf_provincia_2',
        'rf_telefono_1',
        'rf_telefono_2',
        'rp_apellidos_1',
        'rp_apellidos_2',
        'rp_celular_1',
        'rp_celular_2',
        'rp_nombres_1',
        'rp_nombres_2',
        'rp_provincia_1',
        'rp_provincia_2',
        'rp_telefono_1',
        'rp_telefono_2',
        'saldo_financiado',
        'saldo_financiar',
        'seguro_financiado',
        'seguro_meses',
        'tarjeta_credito',
        'tc_tarjeta',
        'tc_valor_tarjeta',
        'tipo_pago',
        'toma_vehiculo',
        'total',
        'tv_avaluo',
        'tv_b_coach',
        'tv_b_trade_in',
        'tv_modelo',
        'tv_valor',
        'v_vehiculo_anio',
        'v_vehiculo_marca',
        'v_vehiculo_modelo',
        'v_vehiculo_valor',
        'valor',
        'valor_accesorios',
        'valor_seguro',
        'vehiculo',
        'venta_vehiculo'
    ];
}
